import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./provider";

const outfit = Outfit({
  subsets: ["latin"],
  weight:["400","500","600","700"]
});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit}`}
      >
        <Providers>
          <ToastContainer theme="dark" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
